### ISSUE TITLE
Build error when KlakSpout folder is moved

### ISSUE THREAD

**Issue by nolwenn-bigoin** [keijiro/KlakSpout#21] opened 2018-10-05 09:39 UTC
Hello,
I'm trying to build my project with the latest KlakSpout release on Unity 2018.2.8f1. If I let the Klak folder directly under Assets the build succeed. But if I moved it under a sub-folder I get this error : error CS0009: Metadata file `C:\Projets\Test\KlakSpout\MyProject\Assets/Plugins/Klak/Spout/Plugin/x64/KlakSpout.dll' does not contain valid metadata. The error stays if I move the folder back to its original location, I have to delete and re-import it again to get a successful build.
Thank you for your help!
Nolwenn

**Comment by keijiro** [comment] 2018-10-05 14:52
I haven't tried moving the plugin folder, but I think you have to close Unity Editor before moving it because the dll file can't be moved without terminating the application process. Did you move the folder while  Editor is running?

**Comment by nolwenn-bigoin** [comment] 2018-10-05 15:20
Yes, I moved the folder inside Unity Editor. But I've just tried moving it in Windows explorer with Unity closed, and the result is still the same.

**Comment by keijiro** [comment] 2018-10-05 16:08
Okay. It reproduced on my side. I'm not sure why but it's resolved after closing and relaunching the Editor. Could you try it? I suspect that there is an issue in the build process of Unity Editor.

**Comment by nolwenn-bigoin** [comment] 2018-10-08 07:59
Hello, yes same on my side, the build works if I relaunch the Editor.

**Comment by keijiro** [comment] 2018-10-09 08:00
Thanks for clarification. I filed a bug report about it as an Editor issue.

Please use the workaround (relaunching Editor) until the issue gets fixed.

**Comment by keijiro** [comment] 2018-10-09 08:00
I'm closing this ticket. Please feel free to reopen for further questions.

**Closed as completed by keijiro** 2018-10-09 08:00 UTC
Labels: question
