### ISSUE TITLE
Send more than 10 Spouts

### ISSUE THREAD

**Issue by eldaville** [keijiro/KlakSpout#8] opened 2018-01-20 02:32 UTC
Hi.. I'm trying to send 15 cameras from Unity to Resolume Arena 6.

For some reason in Resolume I can only see 10 cameras (the first 5 and the last 5).

Is this a limitation in the Resolume side? or is it a limitation in the Unity Side?

**Comment by keijiro** [comment] 2018-01-20 11:34
Actually I've never tried using more than three senders in practice. So... I have no idea!

Thanks for the interesting report! I'll check it when I have free time. My wild guess is that the Spout SDK has some limitations and I implemented the plugin without knowing it.

**Comment by Harvey3141** [comment] 2018-03-22 10:40
In the SpoutSenderNames class, m_MaxSenders is set to 10 in the constructor, increasing this worked for me. I believe there will be some changes in the next release of the SpoutSDK to improve this.

**Comment by keijiro** [comment] 2018-09-06 05:37
This issue is not reproducible with the [latest version](https://github.com/keijiro/KlakSpout/releases/tag/v0.1.3). I used the example sender/receiver provided by the Spout author.

If you still have the issue with your environment, it's considered that the problem is in the Resolume side. Please try contacting the technical support to solve the issue.

I'm closing this issue. Please feel free to reopen for further questions.

**Closed as completed by keijiro** 2018-09-06 05:37 UTC
Labels: bug

**Comment by keijiro** [comment] 2018-09-15 13:54
FYI: I added max senders setting support in v0.2.0. Now you can change the maximum number of senders using SpoutSettings.exe.

https://github.com/keijiro/KlakSpout/releases/tag/v0.2.0
