### ISSUE TITLE
Spout error CS0234

### ISSUE THREAD

**Issue by Latentnaut** [keijiro/KlakSpout#10] opened 2018-03-30 21:49 UTC
Hi Keijiro!

I want to use Spout into Phantom, so I replaced Klak with the newer version, and added Spout. However, I got this error:

Assets/Klak/Spout/Internal/PluginEntry.cs: error CS0234: The type or namespace name 'IntPtr' doesnt exist in the namespace 'Klak.System'. Are you missing an assembly reference?

I don't know how to fix this :-/

**Comment by keijiro** [comment] 2018-04-01 01:31
Did you modified the source code?

I hardly think that this error could happen without modification.

**Comment by Latentnaut** [comment] 2018-04-01 21:38
Clean copy of Phantom, then clean copy of Klak over the one already is in, and clean copy of Spout. That's all.

**Comment by keijiro** [comment] 2018-04-02 02:30
Okay. It reproduced in my side too.

It's caused by the old version of Klak. You have to remove `Assets/Klak/System` directory to resolve it.

I'm closing this ticket. Please feel free to reopen if you still have issues.

**Closed as completed by keijiro** 2018-04-02 02:30 UTC
Labels: question
