### ISSUE TITLE
problem with ATI Radeon HD 6420

### ISSUE THREAD

**Issue by mrarashiyan** [keijiro/KlakSpout#39] opened 2019-10-02 12:58 UTC
Hi,
I've tried to run a Unity project included Spout sender on a pc with AMD Radeon HD 6450 but game crashes and displays "ATI Radeon Driver Stop Working" message. I've run this project on another computer before (with Geforce Graphic).
I just want to know is there any special compatibility for running a Spout Sender in unity?
Thank you

**Comment by keijiro** [comment] 2019-10-02 13:29
KlakSpout doesn't support "CPU mode" that is implemented for old/low-end hardware. The problem is that I don't have any device that requires the CPU mode, so I can't test it.

**Comment by mrarashiyan** [comment] 2019-10-03 05:02
Thank you Keijiro, I used your code in different situations and worked really good. :)
Is there any way that I can use a Spout Sender in "CPU Mode" ?

**Comment by keijiro** [comment] 2019-10-03 05:34
I can't remember details, but I think it's not easy. It may require modification in several parts of the code.

**Comment by keijiro** [comment] 2019-10-08 07:25
I'm closing this issue ticket now as duplication of issue #20

**Closed as completed by keijiro** 2019-10-08 07:25 UTC
Labels: question
