### ISSUE TITLE
Crashing while taking a build

### ISSUE THREAD

**Issue by xeonification** [keijiro/KlakSpout#9] opened 2018-03-19 13:00 UTC
Unity is crashing constantly while trying to build my application with spout sender on the camera. When I turn off the component I am able to build the application.

**Comment by keijiro** [comment] 2018-03-19 15:42
Which version of Unity are you using?

**Comment by xeonification** [comment] 2018-03-19 15:52
2017.3.0 .it was working yesterday. Is there anyways I can give you the
logs ?

**Comment by Andergraw** [comment] 2018-04-14 17:48
First, thank you for your great work, Keijiro, it is absolutely amazing.
We are having exactly the same problem working with Spout, constant crashes on build. 
Using Unity 2017.4.0.
Cheers,

**Comment by keijiro** [comment] 2018-04-15 01:50
First of all, please check the build architecture set to x86_64. KlakSpout doesn't support the 32-bit (x86) architecture.

If you still have problem with that, please send a minimum project that reproduces the problem.

**Comment by Andergraw** [comment] 2018-08-30 10:14
Yep, in my case it was because of that.
Thank you very much!

**Comment by keijiro** [comment] 2018-09-06 05:39
FYI: I added x86 support in the [latest version](https://github.com/keijiro/KlakSpout/releases/tag/v0.1.3).

I'm closing this issue. Please feel free to reopen for further questions.

**Closed as completed by keijiro** 2018-09-06 05:39 UTC
Labels: bug
