### ISSUE TITLE
DLLNotFoundException

### ISSUE THREAD

**Issue by danjaco** [keijiro/KlakSpout#4] opened 2017-07-15 00:43 UTC
I can't seem to get it working. The console fills with DLLNotFoundException: KlakSpout errors, using your test scene or my own tests - although the dll is definitely imported. My Spout version is 2.006 using DX11 mode on Win64.

**Comment by keijiro** [comment] 2017-07-15 16:26
I can't reproduce it. Even I don't have any idea what's happening in it.

Could you try it on another machine and check if it reproduces on it?

**Comment by keijiro** [comment] 2017-08-21 06:19
I'm closing this issue. Please feel free to reopen for further questions.

**Closed as completed by keijiro** 2017-08-21 06:19 UTC
Labels: bug
