### ISSUE TITLE
he type or namespace name 'Spout' does not exist in the namespace 'Klak' (are you missing an assembly reference

### ISSUE THREAD

**Issue by Zudva** [keijiro/KlakSpout#58] opened 2020-09-10 22:40 UTC
Hi!

I have this error in Unity 3d version: 2019.4.8f1:

```
Assets\Script\SourceSelector.cs(7,12): error CS0234: The type or namespace name 'Spout' does not exist in the namespace 'Klak' (are you missing an assembly reference?)


Assets\Script\SourceSelector.cs(13,5): error CS0246: The type or namespace name 'SpoutReceiver' could not be found (are you missing a using directive or an assembly reference?)

```

In Unity 3d version 2020.2.0b1.2959 all work normal.

**Comment by keijiro** [comment] 2020-09-11 01:51
It doesn't reproduce with Unity 2019.4.9f1.

I'm closing this issue as non-reproducible. Please feel free to reopen it if you can share a minimal project that reproduces the issue.

**Comment by spee** [comment] 2020-10-27 16:59
I'm encountering this issue in a project where Klak.Spout is being used as a dependency of another package. After adding the scopedRegistries entry, the dependency gets downloaded, but the same error as OP's is thrown.

**Comment by keijiro** [comment] 2020-10-28 01:04
@spee Could you share a minimal project that reproduces the issue? I think it can be reproduced with a very simple project if nested dependencies are the root cause of the problem.

**Comment by spee** [comment] 2020-10-28 11:36
Thanks for your quick reply. I was going to create an empty project for your but I figured it out already!
In my own package's `.asmdef` file's inspector, I had to add `Klak.Spout.Runtime` to the Assembly Definition References.

**Closed as completed** 2020-10-28 11:53 UTC
Labels: question
