### ISSUE TITLE
Improvement : Add NDI support

### ISSUE THREAD

**Issue by hybridherbst** [keijiro/KlakSpout#3] opened 2017-04-13 06:20 UTC
That's not an issue, but an improvement - having solid support for NewTek's NDI would be awesome as well. It allows sending images over network with a lot less latency than Spout2NDI currently allows.

**Comment by keijiro** [comment] 2017-04-13 06:57
I've received the same feedback from some others, but I've never used NDI so that I have no idea about it. Could you give me some more input?

- Are there any famous apps that support NDI? I'd like to use some of them for experimentation and testing.
- Do you have any idea of why Spout2NDI has such latency issues? I'm not sure if it can be solved by implementing a new native plugin.

**Comment by hybridherbst** [comment] 2017-04-13 13:28
What you can easily use for testing is the NDI Monitor provided by NewTek. It allows you to see the stream on any machines in the local network. Other than that, NewTek's NDI Tools provide ways to access the stream e.g. from AfterEffects, or receiving Streams from VLC, using a Desktop Scan Converter to stream the whole screen content, ...

My best guess is that Spout2NDI is slow because it somehow triggers the "memory" mode of Spout instead of using the DX11 mode, but that's really just a guess.

The correct order of things would probably be something like this:
- open a different render thread and context
- get a DX11 shared handle
- every frame, do a readback in that separate context (to prevent blocking the Unity render thread)
- send that readback data over NDI.

We tested that with a hacked together plugin version, without the separate render context, and had near zero latency (but blocked Unity's threads, which only worked because the texture in question was rather small).

**Comment by benkuper** [comment] 2017-04-18 08:35
Hi, i'm the developer of Spout4Unity, Spout for AfterEffects and part of the development team of the Spout ecosystem.

I think that this feature is not "Spout" related as the spout part of the Spout2NDI workflow is not the cause of the latency, and NDI is actually a completely different technology.

But as people need it and Lynn Jarvis (leadedge) already built a tool for converting Spout to NDI, imho it would be easier and better for everyone to improve the already-existing universal tool rather than implementing it specifically for Unity.

**Comment by keijiro** [comment] 2017-04-18 09:08
Basically I agree with @benkuper. It's better to improve the existing solution than starting a reinventing-the-wheel situation. Or I'd recommend trying another similar solution like [TCPSpout](http://techlife.sg/TCPSpout/).

I'd like to keep this ticket opened just for keeping in mind the topic.

**Comment by hybridherbst** [comment] 2017-04-18 10:37
@benkuper @keijiro thanks for chiming in on this. We did actual tests on that for a project where we needed those network-transmitted images, and the native NDI plugin we hacked together had considerably less latency than either TCPSpout or Spout2NDI. The reasons are outside our understanding, but the fact was that the native solution was the only one that performed good enough, with high enough framerates and image sizes.
I'm more than happy if there gonna be improvements to any of these making it possible. Just saying that right now it's not.

**Comment by benkuper** [comment] 2017-04-18 10:48
If you already managed to have a working solution, then it would be a great idea to contact leadedge (or post on the official spout forum), and share your code with him, see if he can improve the Spout2NDI solution with your technique.
Also, it doesn't seem that Spout2NDI is open source (or i just didn't find it), but i'm sure Lynn won't mind sharing this with you.

**Comment by xiangjunhuang** [comment] 2018-03-15 07:15
It will be great to see NDI integration with spout, by extending the capbility of spout to share video across network. Which I believe is veryuseful.

**Comment by keijiro** [comment] 2018-03-16 02:18
@xiangjunhuang
If you don't mind me asking, which software/hardware do you like to use with NDI? I haven't tried anything about NDI yet, so I'm wondering what the best starter is.

**Comment by benkuper** [comment] 2018-03-16 04:33
@xiangjunhuang There is actually a very useful tool called Spout To NDI  : http://spout.zeal.co/download-spout-to-ndi/
It might be more interesting to keep this conversion out of your software and keep a simple and clean handling of spout texture in your projects, right ?

**Comment by thebelin** [comment] 2018-04-03 04:41
@keijiro Most of the use of NDI (IMO) is to play video in VLC with the NDI plugin and then show that video on a variety of network players, also running VLC. I couldn't get the NDI plugin to work on any version of VLC newer than 2.6. I think it's the famous software you're looking for. The performance is fast and works amazing for pre-encoded video transmission. NDI uses a low latency encoding profile which compresses per frame.

**Comment by xiangjunhuang** [comment] 2018-04-04 05:20
@keijiro NDI is a open standard that Newtek is providing sdk download for free. https://zh.newtek.com/ndi/sdk/. You can find they also providing a set of tools can act as pattern-generator and also a monitor as video receiver for visualization.

**Comment by keijiro** [comment] 2018-04-11 12:47
I'm pleased to announce that I've just released a new plugin that adds NDI support to Unity. Please check the repository below.

https://github.com/keijiro/KlakNDI

I found that NDI is actually useful and super handy for several kinds of applications. I'd like to thank you for valuable input.

I'm closing this issue. Further feedback is welcomed at the KlakNDI issue tracker.

**Closed as completed by keijiro** 2018-04-11 12:47 UTC
Labels: enhancement
