### ISSUE TITLE
Build and Run not working despite normal editor working

### ISSUE THREAD

**Issue by Ethan-N** [keijiro/KlakSpout#51] opened 2020-05-23 02:24 UTC
I am using the Spout Sender script and it seems to be working normally when I use the in-editor play button, but when I try to use build and run, the program still seems to run normally but any Spout Receiver I try to connect gets "Cannot create directx/opengl interop" or other errors along those lines. If I build with the development build setting on, the receiver picks up what I think is the first frame, but doesn't update. After testing many different types of receivers and also a clean Unity project, I believe the bug has something to do with the package and not anything external. Any advice on fixing or other details you might lead to look into it?

**Comment by Ethan-N** [comment] 2020-05-31 16:46
Hi, are there any updates on what the problem might be here? Despite making various tweaks, the same bug still seems to be happening. I am using Unity 2019.3.10f1 if that helps.

**Comment by Ethan-N** [comment] 2020-06-05 06:18
Update on the issue, the problem seems to be that the SpoutSender only send signal when the Sender is attached to a Camera that is currently being used by the display selected. Is this expected behavior, and would there be any way to change it so that the it sends signal even when it is not on the current display?

**Comment by keijiro** [comment] 2020-06-05 06:47
Are you using multiple displays and GPUs?

**Comment by Ethan-N** [comment] 2020-06-05 06:51
Sorry for being unclear, displays referring to the different camera views that multi-display allows in unity, and it's all only running off of one GPU.

**Comment by keijiro** [comment] 2020-06-05 07:56
That's an expected behavior. You have to use the render texture mode for off-screen renders.

**Comment by Ethan-N** [comment] 2020-06-08 00:43
Thanks, the sender now works even when the render is happening off-screen. However, even when switched to render texture mode, the same bug occurs during Build and Run. Is there a specific build setting that could fix this?

**Comment by TShepp** [comment] 2020-06-09 17:48
Hi, I have the same issue. I'm sending a rendered texture from Unity to Openframeworks. It works perfectly fine in Editor mode 
![UnitytoOfxCube](https://user-images.githubusercontent.com/59926533/84181632-323da980-aa57-11ea-8700-88da96951f4d.png)
, but when I try to use a Standalone Build I get the following error message 
![SpoutTest (Debugging) - Microsoft Visual Studio  6_9_2020 1_29_09 PM (2)](https://user-images.githubusercontent.com/59926533/84181651-3a95e480-aa57-11ea-9d26-b1e77d75208a.png). I've removed everything from both my Unity and Ofx projects except for a few basic functions, but the problem still persists.

**Comment by keijiro** [comment] 2020-06-10 01:47
Thanks for additional info. Could you provide the player log? https://docs.unity3d.com/Manual/LogFiles.html

**Comment by TShepp** [comment] 2020-06-10 13:56
Here is the player log. The Unity standalone build continues to run in the background when this error pops up.
[Player.log](https://github.com/keijiro/KlakSpout/files/4758915/Player.log)

**Comment by TShepp** [comment] 2020-06-18 21:20
Update. I switched from using ofxSpout2 to ofxSpout in Openframeworks. This seems to have fixed the crashing issue, but the same problem persists where the rendered texture only sends in Editor mode, but not in the Standalone build.
![UnitytoOfxUpdate](https://user-images.githubusercontent.com/59926533/85072781-a1b64600-b187-11ea-9379-c4f434528637.png)
Here is the player log.
[Player.log](https://github.com/keijiro/KlakSpout/files/4801211/Player.log)
I've used the rendered texture on gameobjects in the scene to confirm that its updating in the Build.

**Comment by bgnt44** [comment] 2020-06-26 14:27
Hello, just to add some insights, first thanks for this amazing plugins, im trying to integrate Unity -> resolume
In Editor/Play mode it works really well but on runtime i get really low fps on the spout sender, i've add a plane in front of the game camera to be sure it wasnt a render texture issue but it really seems that the spoutsender "lost frames"

**Comment by amusedamused** [comment] 2020-12-26 22:52
Is unity versions above 2019.3 not supported? Im working in 2019.4 and i get a spout source in resolume (called main camera) but the screen is all black.

**Comment by amusedamused** [comment] 2020-12-27 20:50
Hi! Im having this issue too, using klak spout and resolume arena 6 , it was working first but then suddenly i get the same error messege. I dident change anything in the settings between it working and not. :O 
also it works fine in the spout reciver, but resolume craches. 
edit: i changed the spout ssettings a bit back and forth and now it works again with the same settings as before when it stoped working both in the editor and standalone build. strange!

**Comment by caseyfarina** [comment] 2021-01-11 06:33
I'm using  Unity 2020.1 and having the same issue. Everything works great sending from the Unity Editor in render texture mode. However, when I build a standalone application, nothing is sent to the Spout Viewer or MadMapper. I appreciate all your work Kiejiro! Arigato gozaimasu!

**Comment by amusedamused** [comment] 2021-01-11 09:35
Have you tried going into the spout settings and resetting them a few
times? That worked for me, its probably a bug on the spout end i would
guess. :)

mån 11 jan. 2021 kl. 07:33 skrev Casey Farina <notifications@github.com>:

**Comment by Fenikkel** [comment] 2021-01-28 12:28
Having the same isue using render texture mode (working without a camera in unity) with the Unity version **2019.4.18f1** and the receiver is Mad Mapper.
 
 Two month ago with the Unity version **2019.3.10f1**, I've done exactly the same with a similar project and it worked perfectly!
 
 Anyway, thanks for all Kejiro! You are the best!

**Comment by Fenikkel** [comment] 2021-02-01 08:47
> 
> 
> Two month ago with the Unity version **2019.3.10f1**, I've done exactly the same with a similar project and it worked perfectly!
> 


I've made a new build with this project and the streaming doesn't work anymore. The build made in 19 oct 2020 works perfectly-

**Comment by Fenikkel** [comment] 2021-02-02 08:14
I cloned the Kejiro's KlakSpout project and test it from there.

**While you have the project opened in Unity (not in play mode), the build won't work.** You need to close before Unity to make it work. Also, it doesn't starts inmediatly. Let pass a few seconds and you will have it in Madmapper at least.

I tested this in differend versions of Madmapper.

**Edit:**
Upgraded Kejiro's project to version 2019.4.18f1 and added some missing modules in the manifest and it's working perfectly.
Maybe the problem is in the scope registry?

**Comment by keijiro** [comment] 2021-07-01 09:47
I rewrote the entire code in v2.0.0. It probably has a similar issue, but it's thought to be a different cause and symptom. So I close this issue for now. Please open a new issue if you find a similar one.

**Closed as completed by keijiro** 2021-07-01 09:47 UTC
Labels: question
