### ISSUE TITLE
Sender - Texture Methd - Image in spout cropped by player window size, wrong aspect ratio

### ISSUE THREAD

**Issue by honda2** [keijiro/KlakSpout#77] opened 2022-01-20 23:58 UTC
I use Sender with Texture Method.
It seems that resolution or aspect ratio of rendered image is taken from main camera or (game view) - rather than the render texture
Then it's blit into proper sized Spout buffer render texture.

When I change size of a game view (or built player), Image in spout gets cropped accordingly

Unity 2020.3.26
Built-in RP
GTX2080S

**Comment by keijiro** [comment] 2022-01-27 09:15
I can't reproduce the issue on 2021.2.8f1 with the built-in render pipeline.

**Comment by keijiro** [comment] 2022-01-27 09:24
I also checked with 2020.3.26, but it doesn't reproduce.

**Comment by keijiro** [comment] 2022-01-27 09:24
I'm closing this issue now as "not reproducible". Please reopen it if it still reproduces (attach a minimal project for reproduction in that case).

**Closed by keijiro** 2022-01-27 09:24 UTC
Labels: question
